### ISSUE TITLE
Bug when doing postcode searching

### ISSUE THREAD

**Issue by liashchynskyi** [getAddress/typeahead#1]
Hello, I'd like to report a bug. This is related to the API not this package.

When I'm searching for postcodes using TypeAhead API, sometimes the results won't pop up. To get it working I need to type a comma after postcode.

For example, `SR32DR` won't show up, but if I type `SR32DR,` I get the results. I don't use this node package, instead I use direct API calls.

1. ![image](https://user-images.githubusercontent.com/17459627/186885116-66614fde-925c-4221-8140-2655dca0d12d.png)
2. ![image](https://user-images.githubusercontent.com/17459627/186885214-8376955e-02e3-4b6a-8bcd-99614aa6f581.png)

1 - Without a comma
2 - With a comma

API call as here - `https://documentation.getaddress.io/Typeahead` using `search: ['postcode']`.

Also it doesn't matter if I use `encodeURI(postcode)` or pass the postcode as it is in the request query params.

**Comment by LeePaulSmith** [comment]
This is not a bug. Typeahead returns suggestions, not the same postcode you have entered.

Please only use GitHub to report code issues

**Comment by liashchynskyi** [comment]
Doesn’t make any sense. What’s the problem in returning the same exact postcode if it is in your system?
